import numpy as np

FILL_VALUE_FLOAT = np.float32(-9999.0)
FILL_VALUE_INT = np.int8(9)

FLAG_GOOD = np.int8(0)
FLAG_ESTIMATED = np.int8(1)
FLAG_SUSPECT = np.int8(2)
FLAG_BAD = np.int8(3)
FLAG_NOT_CHECKED = np.int8(8)
FLAG_MISSING = np.int8(9)

DAYS_PER_JULIAN_YEAR = np.float64(365.25)
SECONDS_PER_DAY = np.float64(86400.0)
LITERS_PER_CUBIC_METER = np.float64(1000.0)
MILLIGRAMS_PER_TON = np.float64(1e9)

# SSL (ton/day) = Q (m3/s) * SSC (mg/L) * 0.0864
SSC_DISCHARGE_TO_SSL_FACTOR = np.float64(
    SECONDS_PER_DAY * LITERS_PER_CUBIC_METER / MILLIGRAMS_PER_TON
)
